Python 3 Fixes
jorticus/pymate pull request #30
Opened 2022-03-09 22:46 UTC by WibblyGhost

Fixing issues that arise when updating this package to Python 3.10.2.

2022-03-10 01:33 UTC, WibblyGhost commented
**Note:** I've changed the name of `matenet.py` to `matenet_main.py` since it conflicts with the folder name `matenet`.

2022-03-12 08:39 UTC, jorticus requested changes

2022-03-12 08:39 UTC, jorticus commented on pymate/matenet/tester.py
> +        print(f"Date: date")
Typo, should be `{date}`

2022-03-12 08:39 UTC, jorticus commented on pymate/value.py
> +        fmt = f"%.{self.resolution}f" % self.value
Make this `{self.resolution:d}` since it's replacing '%d'

2022-03-12 08:39 UTC, jorticus commented on pymate/value.py
> +        fmt = f"%.{self.resolution}f" % self.value
Also this should be in the `__init__` like it was originally to avoid re-forming this string every time `__str__` is called (ok to rename it to `self._fmt` since it's private)

2022-03-12 08:39 UTC, jorticus commented on scan.py
> +        print(f'Port{d.port}: -')
make it `{d.port:d}` since it was originally `%d`

2022-03-12 08:39 UTC, jorticus commented on requirements.txt
> +sqlalchemy
I think split these new additions into a separate `requirements_examples.txt`, since only pyserial is required for the library itself, the other ones are optional (and only used in the examples)

2022-04-09 04:37 UTC, merged